# Site settings
title: Abstracted Away
email: alexandre.zani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Math, tech and whatever else I choose to write about.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abstractedaway.com/" # the base hostname & protocol for your site
github_username:  AlexandreZani
reddit_username:  AlexandreZani

# Build settings
markdown: kramdown
